version: '3.1'
services:
  hr-worker-pg12:
    image: postgres:12-alpine
    container_name: hr-worker-pg12
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: db_hr_worker
    ports:
    - "5434:5432"
  hr-user-pg12:
    image: postgres:12-alpine
    container_name: hr-user-pg12
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: db_hr_user
    ports:
      - "5433:5432"
  hr-eureka-server:
    build: ./hr-eureka-server/
    container_name: hr-eureka-server
    image: hr-eureka-server
    ports:
      - "8761:8761"
  hr-api-gateway-zuul:
    build: ./hr-api-gateway-zuul/
    container_name: hr-api-gateway-zuul
    image: hr-api-gateway-zuul
    ports:
      - "8765:8765"
    depends_on:
      - hr-eureka-server
    environment:
      CONFIG_SERVER_URL: http://hr-config-server:8888
  hr-user:
    build: ./hr-user/
    image: hr-user
    depends_on:
      - hr-eureka-server
      - hr-user-pg12
    environment:
      CONFIG_SERVER_URL: http://hr-config-server:8888
  hr-worker:
    build: ./hr-worker/
    image: hr-worker
    depends_on:
      - hr-eureka-server
      - hr-worker-pg12
    environment:
      CONFIG_SERVER_URL: http://hr-config-server:8888
  hr-payroll:
    build: ./hr-payroll/
    image: hr-payroll
    depends_on:
      - hr-eureka-server
  hr-oauth:
    build: ./hr-oauth/
    image: hr-oauth
    depends_on:
      - hr-eureka-server
    environment:
      CONFIG_SERVER_URL: http://hr-config-server:8888
networks:
  default:
    external:
      name: hr-net
